TropicalStudio/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include

from userextend.forms import AuthenticationNewForm, PasswordChangeNewForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('employee.urls')),
    path('', include('services.urls')),
    path('', include('contact.urls')),
    path("login/", views.LoginView.as_view(form_class=AuthenticationNewForm), name="login"),
    path('password_change/', views.PasswordChangeView.as_view(form_class=PasswordChangeNewForm), name='password_change'),
    path('', include('django.contrib.auth.urls')),
    path('', include('userextend.urls'))
]

home/urls.py
from django.urls import path

from home import views

urlpatterns = [
    path('', views.HomeTemplateView.as_view(), name='homepage'),
]

employee/models.py
from django.db import models


class Employee(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField(max_length=30)
    description = models.TextField(max_length=50)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

services/models.py
from django.db import models
from employee.models import Employee
from django.contrib.auth.models import User


class Service(models.Model):
    name_of_service = models.TextField(max_length=200)
    price = models.IntegerField()
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name_of_service


STATUS = (
    ('draft', 'draft'),
    ('completed', 'completed')
)


class RezervareServicii(models.Model):
    id_service = models.ForeignKey(Service, on_delete=models.CASCADE, null=True)
    id_user = models.IntegerField()
    status = models.CharField(choices=STATUS, max_length=9, default='draft')
    date = models.DateTimeField(null=True)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>TROPICAL STUDIO</title>
    <!-- Bootstrap Icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet"/>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic"
          rel="stylesheet" type="text/css"/>
    <!-- SimpleLightbox plugin CSS-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet"/>
</head>
<body id="page-top">
{% include 'navbar.html' %}
{% block content %}
{% endblock %}
{% include 'footer.html' %}
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- SimpleLightbox plugin JS-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.js"></script>
<!-- Core theme JS-->
<script src="{% static 'js/scripts.js' %}"></script>
<script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
<script src="https://code.jquery.com/jquery-3.7.0.js" integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=" crossorigin="anonymous"></script>
</body>
</html>

templates/footer.html
<footer class="bg-light py-5">
    <div class="container px-4 px-lg-5">
        <div class="small text-center text-muted">Copyright &copy; 2023 - TROPICAL STUDIO</div>
    </div>
</footer>

templates/navbar.html
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="{% url 'homepage' %}">TROPICAL STUDIO</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto my-2 my-lg-0">
                <li class="nav-item"><a class="nav-link" href="#about">Despre noi</a></li>

                {% if user.is_authenticated %}
                    {# dropdown servicii #}
                    {% if perms.services.add_service or perms.services.view_list_of_services %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                               aria-expanded="false">
                                Servicii
                            </a>
                            <ul class="dropdown-menu">
                                {% if perms.services.add_service %}
                                    <li><a class="dropdown-item" href="{% url 'creare-serviciu' %}"> Creaza un
                                        nou serviciu</a></li>
                                {% endif %}
                                {% if perms.services.view_list_of_services %}
                                    <li><a class="dropdown-item" href="{% url 'lista-servicii' %}"> Lista
                                        servicii</a></li>
                                {% endif %}
                            </ul>
                        </li>
                    {% endif %}

                    {# dropdown angajati #}
                    {% if perms.employee.add_employee or perms.employee.view_list_of_employees %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                               aria-expanded="false">
                                Angajati
                            </a>
                            <ul class="dropdown-menu">
                                {% if perms.employee.add_employee %}
                                    <li><a class="dropdown-item" href="{% url 'creare-angajat' %}"> Creaza un
                                        nou angajat</a></li>
                                {% endif %}
                                {% if perms.employee.view_list_of_employees %}
                                    <li><a class="dropdown-item" href="{% url 'lista-angajati' %}"> Lista
                                        angajati</a></li>
                                {% endif %}
                            </ul>
                        </li>
                    {% endif %}
                {% endif %}

                <li class="nav-item"><a class="nav-link" href="{% url 'contact' %}">Contact</a></li>
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            Bine ai venit, {{ user.username }} !
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'programarile-mele' %}">Programarile mele</a></li>
                            <li><a class="dropdown-item" href="{% url 'password_change' %}"> Schimba parola</a></li>
                            <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Login</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'creare-user' %}">Inregistreaza-te</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>